// <copyright file="Leaderboards.cs" company="Jan Ivar Z. Carlsen, Sindri Jóelsson">
// Copyright (c) 2016 Jan Ivar Z. Carlsen, Sindri Jóelsson. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.
// </copyright>

namespace CloudOnce
{
    using Internal;

    /// <summary>
    /// Provides access to leaderboards registered via the CloudOnce Editor.
    /// This file was automatically generated by CloudOnce. Do not edit.
    /// </summary>
    public static class Leaderboards
    {
        private static readonly UnifiedLeaderboard s_googlePlayLeaderboard = new UnifiedLeaderboard("GooglePlayLeaderboard",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkI29SRhbwNEAIQAQ"
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_AMAZON
            ""
#else
            "GooglePlayLeaderboard"
#endif
            );

        public static UnifiedLeaderboard GooglePlayLeaderboard
        {
            get { return s_googlePlayLeaderboard; }
        }

        private static readonly UnifiedLeaderboard s_iosleaderboard = new UnifiedLeaderboard("iosleaderboard",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            "wall_ball_scores"
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_AMAZON
            ""
#else
            "iosleaderboard"
#endif
            );

        public static UnifiedLeaderboard iosleaderboard
        {
            get { return s_iosleaderboard; }
        }
    }
}
